/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cliente.vistas;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;

/**
 *
 * @author adrianfelipegp
 */
public class FrmNotificacion extends javax.swing.JFrame {

    /**
     * Creates new form FrmNotificacion
     */
    public FrmNotificacion(int id,String contexto, String indicadores) {
        initComponents();
        this.setVisible(true);
        this.lblContexto.setText(contexto);
        this.txtIndicadores.setText(indicadores);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setTitle("Notificacion Cliente Id:"+id);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblEncabezado = new javax.swing.JLabel();
        lblContexto = new javax.swing.JLabel();
        lblIndicadoresTexto = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtIndicadores = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 400));
        setMinimumSize(new java.awt.Dimension(500, 400));
        setPreferredSize(new java.awt.Dimension(400, 500));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEncabezado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblEncabezado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEncabezado.setText("Nueva Alerta");
        getContentPane().add(lblEncabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 500, 40));

        lblContexto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblContexto.setText("Contexto");
        lblContexto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblContexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 500, 30));

        lblIndicadoresTexto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblIndicadoresTexto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIndicadoresTexto.setText("Indicadores Fuera de Rango");
        getContentPane().add(lblIndicadoresTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 500, 50));

        txtIndicadores.setColumns(2);
        txtIndicadores.setRows(7);
        txtIndicadores.setMaximumSize(new java.awt.Dimension(600, 600));
        txtIndicadores.setMinimumSize(new java.awt.Dimension(400, 300));
        jScrollPane1.setViewportView(txtIndicadores);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 500, 250));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Desarrollado por: Adrian Gironza, Santiago Acuña, Andres Rubiano");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 394, 500, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        
    }//GEN-LAST:event_formWindowClosed

   
    /**
     * @param args the command line arguments
     */
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblContexto;
    private javax.swing.JLabel lblEncabezado;
    private javax.swing.JLabel lblIndicadoresTexto;
    private javax.swing.JTextArea txtIndicadores;
    // End of variables declaration//GEN-END:variables
}
